name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v5

      - name: setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python }}"
          cache: pip

      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r test-requirements.txt

      - name: pip freeze
        run: pip freeze

      - name: test
        run: |
          pytest --cov escapism -v tests

      - uses: codecov/codecov-action@v5
